// Generated by LiveScript 1.6.0
(function(){
  var ref$, get, post, port, url, invoice;
  ref$ = require('superagent'), get = ref$.get, post = ref$.post;
  port = require('../config.json').port;
  url = "https://127.0.0.1:" + port;
  invoice = {
    amount: '100',
    amountCurrency: 'USD',
    callbackUrl: 'https://google.com.ua',
    invoiceCurrency: 'BTC'
  };
  get(url + "/invoice/create", invoice, function(err, data){
    return console.log(err, data);
  });
}).call(this);
